development:
  cloud_name: dpjulry83
  api_key: '233958554793257'
  api_secret: tC2wLZE57ZMJecxwYxrjXpBoPtI
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dpjulry83
  api_key: '233958554793257'
  api_secret: tC2wLZE57ZMJecxwYxrjXpBoPtI
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dpjulry83
  api_key: '233958554793257'
  api_secret: tC2wLZE57ZMJecxwYxrjXpBoPtI
  enhance_image_tag: true
  static_image_support: false